### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by svs** [paktek123/elasticsearch-crystal#2]
```
Error in run.cr:1: while requiring "elasticsearch-crystal/elasticsearch/api"

require "elasticsearch-crystal/elasticsearch/api"
^

in lib/elasticsearch-crystal/src/elasticsearch/api.cr:4: while requiring "./api/version": can't find file './api/version' relative to '/Users/svs/src/crystal/a/lib/elasticsearch-crystal/src/elasticsearch'

require "./api/version"
```
There is no file called 'version.cr' in the bundle.

```
ls lib/elasticsearch-crystal/src/elasticsearch/api
actions   namespace utils.cr
```

```
name: shards
version: 0.1.0

dependencies:
  elasticsearch-crystal:
    github: paktek123/elasticsearch-crystal
    version: ~> 0.11
```

I'm super new to Crystal so could be a silly mistake on my part. Thanks
